<?php

namespace ContainerFhSiyEb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavoriteMovieRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\FavoriteMovie\Infrastructure\DB\SQLite\Repository\FavoriteMovieRepository' shared autowired service.
     *
     * @return \App\FavoriteMovie\Infrastructure\DB\SQLite\Repository\FavoriteMovieRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryProxy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/FavoriteMovie/Domain/Repository/IFavoriteMovieRepository.php';
        include_once \dirname(__DIR__, 4).'/src/FavoriteMovie/Infrastructure/DB/SQLite/Repository/FavoriteMovieRepository.php';

        return $container->privates['App\\FavoriteMovie\\Infrastructure\\DB\\SQLite\\Repository\\FavoriteMovieRepository'] = new \App\FavoriteMovie\Infrastructure\DB\SQLite\Repository\FavoriteMovieRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
