<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTwSB8SU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTwSB8SU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTwSB8SU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTwSB8SU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTwSB8SU\App_KernelDevDebugContainer([
    'container.build_hash' => 'TwSB8SU',
    'container.build_id' => '92681b62',
    'container.build_time' => 1748827778,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTwSB8SU');
