<?php

namespace ContainerTwSB8SU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostFavoriteMovieControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\FavoriteMovie\Presentation\Rest\V1\PostFavoriteMovieController' shared autowired service.
     *
     * @return \App\FavoriteMovie\Presentation\Rest\V1\PostFavoriteMovieController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/FavoriteMovie/Presentation/Rest/V1/PostFavoriteMovieController.php';
        include_once \dirname(__DIR__, 4).'/src/FavoriteMovie/Application/Service/AddFavoriteMovieService.php';

        $a = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        $container->services['App\\FavoriteMovie\\Presentation\\Rest\\V1\\PostFavoriteMovieController'] = $instance = new \App\FavoriteMovie\Presentation\Rest\V1\PostFavoriteMovieController(new \App\FavoriteMovie\Application\Service\AddFavoriteMovieService($a, ($container->privates['App\\FavoriteMovie\\Infrastructure\\DB\\SQLite\\Repository\\FavoriteMovieRepository'] ?? $container->load('getFavoriteMovieRepositoryService'))), $a);

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\FavoriteMovie\\Presentation\\Rest\\V1\\PostFavoriteMovieController', $container));

        return $instance;
    }
}
